# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Msg1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Msg1
pod 'Alamofire', '~> 5.0.0-rc.2'

  target 'Msg1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Msg1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
